Repository ray-project/kuberay, pull requests merged in 2024-07, with the labels that each got.

#2214 [Feat][RayCluster] Introduce the RayClusterStatus.Conditions field
  docs/reference/api.md
  helm-chart/kuberay-operator/crds/ray.io_rayclusters.yaml
  helm-chart/kuberay-operator/crds/ray.io_rayjobs.yaml
  helm-chart/kuberay-operator/crds/ray.io_rayservices.yaml
  ray-operator/apis/ray/v1/raycluster_types.go
  ray-operator/apis/ray/v1/zz_generated.deepcopy.go
  ray-operator/config/crd/bases/ray.io_rayclusters.yaml
  ray-operator/config/crd/bases/ray.io_rayjobs.yaml
  ray-operator/config/crd/bases/ray.io_rayservices.yaml
  ray-operator/pkg/client/applyconfiguration/ray/v1/rayclustercondition.go
  ray-operator/pkg/client/applyconfiguration/ray/v1/rayclusterstatus.go
Labels: crd observability

#2184 Support Apache YuniKorn as one batch scheduler option
  ray-operator/controllers/ray/batchscheduler/schedulermanager.go
  ray-operator/controllers/ray/batchscheduler/yunikorn/yunikorn_scheduler.go
  ray-operator/controllers/ray/batchscheduler/yunikorn/yunikorn_scheduler_test.go
Labels: 1.2.0

#2266 [Feature] REP 54: Add PodName to the HeadInfo
  helm-chart/kuberay-operator/crds/ray.io_rayclusters.yaml
  helm-chart/kuberay-operator/crds/ray.io_rayjobs.yaml
  helm-chart/kuberay-operator/crds/ray.io_rayservices.yaml
  ray-operator/apis/ray/v1/raycluster_types.go
  ray-operator/config/crd/bases/ray.io_rayclusters.yaml
  ray-operator/config/crd/bases/ray.io_rayjobs.yaml
  ray-operator/config/crd/bases/ray.io_rayservices.yaml
  ray-operator/controllers/ray/common/association.go
  ray-operator/controllers/ray/common/association_test.go
  ray-operator/controllers/ray/raycluster_controller.go
  ray-operator/controllers/ray/raycluster_controller_unit_test.go
  ray-operator/controllers/ray/rayservice_controller.go
  ray-operator/pkg/client/applyconfiguration/ray/v1/headinfo.go
Labels: 1.2.0

#2267 [RayCluster] improve generated pod names for Ray clusters
  ray-operator/controllers/ray/raycluster_controller.go
  ray-operator/controllers/ray/utils/util.go
  ray-operator/controllers/ray/utils/util_test.go
Labels: 1.2.0

#2261 [Feature][RayCluster]: Implement the HeadReady condition
  helm-chart/kuberay-operator/templates/_helpers.tpl
  helm-chart/kuberay-operator/templates/deployment.yaml
  helm-chart/kuberay-operator/values.yaml
  ray-operator/apis/ray/v1/raycluster_types.go
  ray-operator/controllers/ray/raycluster_controller.go
  ray-operator/controllers/ray/raycluster_controller_unit_test.go
  ray-operator/controllers/ray/rayservice_controller.go
  ray-operator/controllers/ray/utils/util.go
  ray-operator/controllers/ray/utils/util_test.go
Labels: 1.2.0

#2272 [Bug] Issue with glibc version GLIBC_2.34 and GLIBC_2.32 not found in earlier operator tags
  ray-operator/Dockerfile
  ray-operator/Dockerfile.buildx
Labels: P0

#2271 Add RayClusterReady Condition Type
  ray-operator/apis/ray/v1/raycluster_types.go
  ray-operator/controllers/ray/raycluster_controller.go
  ray-operator/controllers/ray/raycluster_controller_unit_test.go
  ray-operator/controllers/ray/utils/util.go
  ray-operator/controllers/ray/utils/util_test.go
Labels: 1.2.0
