Repository ray-project/kuberay, pull requests merged in 2024-08, with the labels that each got.

#2268 kuberay autoscaler pod use same command and args as ray head container
  ray-operator/controllers/ray/common/pod.go
  ray-operator/controllers/ray/common/pod_test.go
Labels: 1.2.0

#2262 Support disable leader election for manager go binary via Values.yaml to mitigate kuberay restarts
  helm-chart/kuberay-operator/templates/deployment.yaml
  helm-chart/kuberay-operator/values.yaml
Labels: 1.2.0

#2283 [Test][RayCluster] Add envtests for RayCluster conditions
  ray-operator/controllers/ray/raycluster_controller_test.go
Labels: 1.2.0

#2263 Add unit test for cluster get and add steps in workflows
  .github/workflows/test-job.yaml
  kubectl-plugin/cmd/kubectl-ray.go
  kubectl-plugin/go.mod
  kubectl-plugin/go.sum
  kubectl-plugin/pkg/cmd/cluster/cluster.go
  kubectl-plugin/pkg/cmd/cluster/get.go
  kubectl-plugin/pkg/cmd/cluster/get_test.go
  kubectl-plugin/pkg/cmd/ray.go
Labels: 1.2.0

#2284 [Helm] Enable leader election when leaderElectionEnabled is not set
  helm-chart/kuberay-operator/templates/deployment.yaml
  helm-chart/kuberay-operator/values.yaml
Labels: 1.2.0

#2287 Add basic e2e test for kubectl plugin
  .github/workflows/e2e-tests-reusable-workflow.yaml
  .github/workflows/e2e-tests.yaml
  kubectl-plugin/go.mod
  kubectl-plugin/test/e2e/kubectl_ray_test.go
Labels: 1.2.0

#2217 [RayCluster][Fix] evicted head-pod can be recreated or restarted
  ray-operator/controllers/ray/raycluster_controller.go
  ray-operator/controllers/ray/raycluster_controller_unit_test.go
Labels: 1.2.0

#2301 Add RayClusterProvisioned Condition Type
  ray-operator/apis/ray/v1/raycluster_types.go
  ray-operator/controllers/ray/raycluster_controller.go
  ray-operator/controllers/ray/raycluster_controller_test.go
  ray-operator/controllers/ray/raycluster_controller_unit_test.go
Labels: 1.2.0

#2304 RayClusterProvisioned status should be set while cluster is being provisioned for the first time
  ray-operator/apis/ray/v1/raycluster_types.go
  ray-operator/controllers/ray/raycluster_controller.go
  ray-operator/controllers/ray/raycluster_controller_test.go
  ray-operator/controllers/ray/raycluster_controller_unit_test.go
Labels: 1.2.0

#2313 [release blocker][v1.2.0] Fix HA OOM issue
  ray-operator/config/samples/ray-service.high-availability.yaml
Labels: 1.2.0

#2321 [RayJob] allow create verb for services/proxy, which is required for HTTPMode
  helm-chart/kuberay-operator/templates/_helpers.tpl
  helm-chart/kuberay-operator/templates/deployment.yaml
  helm-chart/kuberay-operator/values.yaml
  ray-operator/config/rbac/role.yaml
  ray-operator/controllers/ray/rayjob_controller.go
  ray-operator/controllers/ray/utils/dashboard_httpclient.go
Labels: 1.2.0, release-blocker

#2325 Bump go to 1.22.4 to fix ray-operator vulnerabilities
  apiserver/go.mod
  ray-operator/go.mod
Labels: 1.2.0, release-blocker

#2320 Generate RayCluster Hash on KubeRay Version Change
  ray-operator/controllers/ray/rayservice_controller.go
  ray-operator/controllers/ray/rayservice_controller_unit_test.go
  ray-operator/controllers/ray/utils/constant.go
Labels: 1.2.0, release-blocker

#2330 [Fix][Sample-Yaml] Increase ray head CPU resource for pytorch minst
  ray-operator/config/samples/pytorch-mnist/ray-job.pytorch-mnist.yaml
Labels: release-blocker

#2295 [Refactor][kubectl-plugin] Rename filenames and variables based on kubectl repo
  kubectl-plugin/pkg/cmd/cluster/cluster_get.go
  kubectl-plugin/pkg/cmd/cluster/cluster_get_test.go
Labels: 1.3.0

#2286 raycluster_controller: generate events for failed pod creation
  ray-operator/controllers/ray/raycluster_controller.go
  ray-operator/controllers/ray/raycluster_controller_unit_test.go
Labels: crd observability, 1.3.0
