Repository ray-project/kuberay, pull requests merged in 2024-09, with the labels that each got.

#2288 [Feature][RayCluster]: Deprecate the RayCluster .Status.State field
  ray-operator/apis/ray/v1/raycluster_types.go
  ray-operator/apis/ray/v1alpha1/raycluster_types.go
  ray-operator/controllers/ray/raycluster_controller.go
  ray-operator/controllers/ray/raycluster_controller_unit_test.go
  ray-operator/controllers/ray/rayjob_controller.go
  ray-operator/controllers/ray/rayjob_controller_test.go
  ray-operator/controllers/ray/suite_helpers_test.go
  ray-operator/test/support/ray.go
Labels: crd observability, 1.3.0

#2290 [Feature] Display reconcile failures as events (ServiceAccount)
  ray-operator/controllers/ray/raycluster_controller.go
  ray-operator/controllers/ray/utils/constant.go
Labels: crd observability, 1.3.0

#2300 Add batch-scheduler option, deprecate enable-batch-scheduler option
  helm-chart/kuberay-operator/templates/deployment.yaml
  helm-chart/kuberay-operator/values.yaml
  ray-operator/apis/config/v1alpha1/config_utils.go
  ray-operator/apis/config/v1alpha1/config_utils_test.go
  ray-operator/apis/config/v1alpha1/configuration_types.go
  ray-operator/controllers/ray/batchscheduler/schedulermanager.go
  ray-operator/controllers/ray/batchscheduler/schedulermanager_test.go
  ray-operator/controllers/ray/raycluster_controller.go
  ray-operator/controllers/ray/suite_test.go
  ray-operator/main.go
Labels: 1.3.0

#2298 [Feature][kubectl-plugin] Implement kubectl ray session
  kubectl-plugin/go.mod
  kubectl-plugin/go.sum
  kubectl-plugin/pkg/cmd/ray.go
  kubectl-plugin/pkg/cmd/session/session.go
  kubectl-plugin/pkg/cmd/session/session_test.go
Labels: 1.3.0

#2296 Add kubectl ray cluster log command
  kubectl-plugin/README.md
  kubectl-plugin/pkg/cmd/log/log.go
  kubectl-plugin/pkg/cmd/log/log_test.go
  kubectl-plugin/pkg/cmd/ray.go
Labels: 1.3.0

#2371 Remove default option for batch scheduler name
  helm-chart/kuberay-operator/values.yaml
  ray-operator/apis/config/v1alpha1/config_utils.go
  ray-operator/apis/config/v1alpha1/config_utils_test.go
  ray-operator/controllers/ray/batchscheduler/schedulermanager.go
  ray-operator/controllers/ray/batchscheduler/schedulermanager_test.go
  ray-operator/main.go
Labels: 1.3.0

#2364 [Feat][RayJob] UserMode SubmissionMode
  helm-chart/kuberay-operator/crds/ray.io_rayjobs.yaml
  ray-operator/apis/ray/v1/rayjob_types.go
  ray-operator/config/crd/bases/ray.io_rayjobs.yaml
  ray-operator/controllers/ray/rayjob_controller.go
  ray-operator/controllers/ray/rayjob_controller_test.go
  ray-operator/controllers/ray/suite_helpers_test.go
  ray-operator/controllers/ray/utils/constant.go
Labels: 1.3.0

#2384 [Feat][kubectl-plugin] Add instructions for static shell completion
  kubectl-plugin/README.md
  kubectl-plugin/pkg/cmd/ray.go
Labels: 1.3.0

#2379 [Feat][Kubectl-Plugin] Implement kubectl session for RayJob and RayService
  kubectl-plugin/go.mod
  kubectl-plugin/pkg/cmd/session/session.go
  kubectl-plugin/pkg/cmd/session/session_test.go
  kubectl-plugin/pkg/util/client/client.go
  kubectl-plugin/pkg/util/client/client_test.go
  kubectl-plugin/pkg/util/types.go
Labels: 1.3.0

#2306 [RayJob] Add Failure Feedback (log and event) for Failed k8s Creation Task
  ray-operator/controllers/ray/rayjob_controller.go
  ray-operator/controllers/ray/rayjob_controller_unit_test.go
Labels: 1.3.0

#2405 [Feat][kubectl-plugin] Add Long, Example, shell completion for kubectl ray log
  kubectl-plugin/pkg/cmd/log/log.go
Labels: 1.2.2

#2407 [Build][kubectl-plugin] Add release script for kubectl plugin
  .github/workflows/release.yaml
  .krew.yaml
  .pre-commit-config.yaml
  docs/development/release.md
  kubectl-plugin/.gitignore
  kubectl-plugin/.goreleaser.yaml
Labels: 1.2.2
