Repository ray-project/kuberay, pull requests merged in 2025-06, with the labels that each got.

#3708 [apiserver] Use ClusterIP instead of NodePort for KubeRay API server service
  apiserver/Autoscaling.md
  apiserver/CreatingServe.md
  apiserver/HACluster.md
  apiserver/JobSubmission.md
  apiserver/Monitoring.md
  apiserver/README.md
  helm-chart/kuberay-apiserver/README.md
  helm-chart/kuberay-apiserver/values.yaml
Labels: 1.4.0, branch-cut-blocker

#3707 [Test][Autoscaler] deflaky unexpected dead actors in tests by higher resource requests
  ray-operator/test/e2eautoscaler/raycluster_autoscaler_part2_test.go
  ray-operator/test/e2eautoscaler/raycluster_autoscaler_test.go
  ray-operator/test/e2eautoscaler/support.go
Labels: 1.4.0, branch-cut-blocker

#3742 [fix][operator] RayJob.Status.RayJobStatusInfo.EndTime nil deref error
  ray-operator/controllers/ray/rayjob_controller.go
Labels: 1.4.0, branch-cut-blocker

#3700 [Test][Autoscaler] deflaky unexpected dead actors in tests by setting max_restarts=-1
  ray-operator/test/e2eautoscaler/create_detached_actor.py
Labels: 1.4.0, branch-cut-blocker

#3734 Improve Grafana Dashboard
  config/grafana/KubeRay-Operator.json
Labels: release-blocker, 1.4.0

#3698 [Release] Update KubeRay version references for 1.4.0-rc.0
  go.mod
  helm-chart/kuberay-apiserver/Chart.yaml
  helm-chart/kuberay-apiserver/values.yaml
  helm-chart/kuberay-operator/Chart.yaml
  helm-chart/kuberay-operator/README.md
  helm-chart/kuberay-operator/README.md.gotmpl
  helm-chart/kuberay-operator/values.yaml
  helm-chart/ray-cluster/Chart.yaml
  ray-operator/config/default-with-webhooks/kustomization.yaml
  ray-operator/config/default/kustomization.yaml
  ray-operator/controllers/ray/utils/constant.go
Labels: 1.4.0

#3517 Added Ray-Serve Config For LLMs
  ray-operator/config/samples/ray-service.llm-serve.yaml
Labels: release-blocker, 1.4.0

#3594 [DOCS] KubeRay APIServer V2 document
  apiserversdk/Installation.md
  apiserversdk/README.md
  apiserversdk/Troubleshooting.md
  apiserversdk/docs/raycluster-quickstart.md
  apiserversdk/docs/rayjob-quickstart.md
  apiserversdk/docs/rayservice-quickstart.md
Labels: release-blocker, 1.4.0

#3782 Update update-ray-job.kueue-toy-sample.yaml
  ray-operator/config/samples/ray-job.kueue-toy-sample.yaml
Labels: release-blocker, 1.4.0

#3786 Remove vLLM examples in favor of Ray Serve LLM
  ray-operator/config/samples/vllm/ray-service.vllm.yaml
  ray-operator/config/samples/vllm/serve.py
Labels: release-blocker, 1.4.0

#3805 [Helm Chart] Set honorLabel of serviceMonitor to `true`
  helm-chart/kuberay-operator/README.md
  helm-chart/kuberay-operator/values.yaml
Labels: release-blocker, 1.4.0
